apiVersion: v1
kind: Service
metadata:
  name: authserver-service
spec:
  selector:
    app: authserver
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 5000
    nodePort: 31110